global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'dgraph'
    scrape_interval: 15s
    metrics_path: '/debug/prometheus_metrics'
    static_configs:
      - targets:
        - 'localhost:8080'
        - 'localhost:6080'